---
- name: Origin on oVirt
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - playbook_vars.yml
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  roles:
    - oVirt.origin-on-ovirt
