---
# The OpenShift distribution to install
openshift_distribution: origin
engine_cafile: ""
ovirt_cluster_name: Default
ovirt_template_memory: 4Gib
ovirt_template_cpu: 2
ovirt_template_disk_storage: hosted_storage
ovirt_template_timeout: 1200
ovirt_template_disk_size: 10GiB
ovirt_template_nics:
  - name: nic1
    profile_name: ovirtmgmt
    interface: virtio
wait_for_ip: True
openshift_ansible_files_path: /root
openshift_ansible_role_path: /usr/share/ansible/openshift-ansible
