---
dependencies:
  - oVirt.ovirt-include-vars-files
  - oVirt.ovirt-fluentd/read-local-pki-files
  - oVirt.ovirt-fluentd/read-local-engine-defaults
  - oVirt.ovirt-fluentd/ovirt-fluentd-package
  - oVirt.ovirt-fluentd/fluentd-setup
  - oVirt.ovirt-fluentd/set-fluentd-system-configurations
  - oVirt.ovirt-fluentd/client
  - oVirt.ovirt-fluentd/http-input
  - oVirt.ovirt-fluentd/ovirt-host
  - oVirt.ovirt-fluentd/ovirt-engine
  - oVirt.ovirt-fluentd/ovirt-host-logs
  - oVirt.ovirt-fluentd/ovirt-engine-logs
  - oVirt.ovirt-fluentd/ovirt-post-processing-common
