- name: Run initial validations sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.initial-validations"

- name: Run fluentd sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.fluentd"

- name: Run collectd sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.collectd"

