- name: Run initial validations sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.initial-validations"

- name: Run fluentd sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.fluentd"
  when:
    - failed_validation is undefined

- name: Run collectd sub-role
  include_role:
    name: "oVirt.metrics/roles/oVirt.collectd"
  when:
    - failed_validation is undefined
