---
- name: Place collectd_postgresql config
  template:
    src: collectd_postgresql.conf.j2
    dest: /etc/collectd.d/20-collectd_postgresql.conf
  notify: restart collectd
  when: configure_collectd_postgresql
