---
- name: Install collectd package and plugins
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ collectd_host_plugin_packages }}'
  when: manage_packages|default(true)
  notify: restart collectd
