---
- name: Check environment name length
  fail:
    msg: "'{{ ovirt_env_name }}' length must be up to 49 characters. Please update ovirt_env_name in the config.yml file"
  when:  ovirt_env_name | length > 49

- name: Check environment name does not start with a number
  fail:
    msg: "'{{ ovirt_env_name }}' can not begin with a number. Please update ovirt_env_name in the config.yml file"
  when: ovirt_env_name | match('^[0-9]')

- name: Check environment name does not start a with dash
  fail:
    msg: "'{{ ovirt_env_name }}' can not begin with a hyphen ('-'). Please update ovirt_env_name in the config.yml file"
  when: ovirt_env_name.startswith('-')

- name: Check environment name does not end a with dash
  fail:
    msg: "'{{ ovirt_env_name }}' can not end with a hyphen ('-'). Please update ovirt_env_name in the config.yml file"
  when: ovirt_env_name.endswith('-')

- name: Check environment name includes only alphanum and dashes
  fail:
    msg: "'{{ ovirt_env_name }}' can include only alpahnumerics and hyphens ('-'). Please update ovirt_env_name in the config.yml file"
  when: ovirt_env_name | match('.*[^a-zA-Z0-9-].*')
