---
openshift_ansible_files_path: /root

# The number of day the curator will not delete ovirt metrics records
ovirt_metrics_curator_delete_days: 3

logging_namespace: openshift-logging

viaq_metrics_store: true
