---
- name: Check if oVirt metrics config.yml file exist
  stat:
    path: "{{ ovirt_metrics_config_yml_file }}"
  register: stat_result
  run_once: true
  delegate_to: localhost

- name: Include oVirt metrics config.yml file
  include_vars:
    file: '{{ ovirt_metrics_config_yml_file }}'
  when: stat_result.stat.exists == True
  run_once: true
  delegate_to: localhost

- name: Include oVirt metrics config.yml.d vars directory
  include_vars:
    dir: '{{ ovirt_metrics_config_yml_dir }}'
    ignore_files: ['README.md']
  run_once: true
  delegate_to: localhost

- name: "If output plugin is elasticsearch, validate host address is set"
  debug:
    msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
  when:
    - fluentd_elasticsearch_host == "elasticsearch-server.example.com" or fluentd_elasticsearch_host == "" or fluentd_elasticsearch_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  delegate_to: localhost

- meta: end_play
  when:
    - fluentd_elasticsearch_host == "elasticsearch-server.example.com" or fluentd_elasticsearch_host == "" or fluentd_elasticsearch_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  run_once: true
  delegate_to: localhost

- name: "If output plugin is fluentd, validate host address is set"
  debug:
    msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
  when:
    - fluentd_fluentd_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "fluentd"
  run_once: true
  delegate_to: localhost

- meta: end_play
  when:
    - fluentd_fluentd_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "fluentd"
  run_once: true
  delegate_to: localhost

- name: "Validate viaq_metrics_store parameter is set"
  debug:
    msg: "viaq_metrics_store parameter is mandatory. Please set the parameter to 'true' or 'false'."
  run_once: true
  when:
    - viaq_metrics_store is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  delegate_to: localhost

- meta: end_play
  when:
    - viaq_metrics_store is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  run_once: true
  delegate_to: localhost

- name: "Validate viaq_metrics_store parameter"
  debug:
    msg: "{{ viaq_metrics_store }} is not a valid value for viaq_metrics_store parameter. Please set the parameter to 'true' or 'false'"
  run_once: true
  when:
    - viaq_metrics_store != true
    - viaq_metrics_store != false
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  delegate_to: localhost

- meta: end_play
  when:
    - viaq_metrics_store != true
    - viaq_metrics_store != false
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
  run_once: true
  delegate_to: localhost

- name: "Validate openshift_deployment_type parameter is set"
  debug:
    msg: "openshift_deployment_type is mandatory, when deploying Viaq Logging. Please set the parameter to 'origin' or 'openshift-enterprise'"
  run_once: true
  when:
    - openshift_deployment_type is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == "yes"
  delegate_to: localhost

- meta: end_play
  when:
    - openshift_deployment_type is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == "yes"
  run_once: true
  delegate_to: localhost

- name: "Validate openshift_deployment_type parameter"
  debug:
    msg: "{{ openshift_deployment_type }} is not a valid value for openshift_deployment_type parameter. Please set the parameter to 'origin' or 'openshift-enterprise'"
  run_once: true
  when:
    - openshift_deployment_type != "origin"
    - openshift_deployment_type != "openshift-enterprise"
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == "yes"
  delegate_to: localhost

- meta: end_play
  when:
    - openshift_deployment_type != "origin"
    - openshift_deployment_type != "openshift-enterprise"
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == "yes"
  run_once: true
  delegate_to: localhost

