---
- name: "If output plugin is elasticsearch, validate host address is set"
  debug:
    msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
  when:
    - fluentd_elasticsearch_host == "elasticsearch-server.example.com" or fluentd_elasticsearch_host == "" or fluentd_elasticsearch_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"

- meta: end_play
  when:
    - fluentd_elasticsearch_host == "elasticsearch-server.example.com" or fluentd_elasticsearch_host == "" or fluentd_elasticsearch_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"

- name: "If output plugin is fluentd, validate host address is set"
  debug:
    msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
  when:
    - fluentd_fluentd_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "fluentd"

- meta: end_play
  when:
    - fluentd_fluentd_host is undefined
    - fluentd_output_plugin|default("elasticsearch") == "fluentd"

- name: "Validate viaq_metrics_store parameter is set"
  fail:
    msg: "viaq_metrics_store parameter is mandatory. Please set the parameter to 'true' or 'false'."
  when:
    - viaq_metrics_store is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"

- name: "Validate viaq_metrics_store parameter"
  fail:
    msg: "{{ viaq_metrics_store }} is not a valid value for viaq_metrics_store parameter. Please set the parameter to 'true' or 'false'"
  when:
    - viaq_metrics_store|default("") != true
    - viaq_metrics_store|default("") != false
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"

- name: "Validate openshift_deployment_type parameter is set"
  fail:
    msg: "openshift_deployment_type is mandatory, when deploying Viaq Logging. Please set the parameter to 'origin' or 'openshift-enterprise'"
  when:
    - openshift_deployment_type is undefined
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == true

- name: "Validate openshift_deployment_type parameter"
  fail:
    msg: "{{ openshift_deployment_type }} is not a valid value for openshift_deployment_type parameter. Please set the parameter to 'origin' or 'openshift-enterprise'"
  when:
    - openshift_deployment_type|default("") != "origin"
    - openshift_deployment_type|default("") != "openshift-enterprise"
    - fluentd_output_plugin|default("elasticsearch") == "elasticsearch"
    - viaq_metrics_store == true

- set_fact:
    passed_validation: true

