---
#  notify: set failed validation

# Task required for backwards compatibility task
- name: Update fluentd_elasticsearch_host
  set_fact:
    fluentd_elasticsearch_host: ""
  when: (fluentd_elasticsearch_host == "elasticsearch-server.example.com") or (fluentd_elasticsearch_host is undefined)

- name: Update fluentd_elasticsearch_host if elasticsearch_host is defined
  set_fact:
    fluentd_elasticsearch_host: "{{ elasticsearch_host }}"
  when: elasticsearch_host is defined

- name: Set elasticsearch_host if undefined and fluentd_elasticsearch_host is defined
  set_fact:
    elasticsearch_host: "{{ fluentd_elasticsearch_host }}"
  when:
    - elasticsearch_host is undefined

- name: Set logging_output_type if undefined and fluentd_elasticsearch_host is defined
  set_fact:
    logging_output_type: "{{ fluentd_output_plugin }}"
  when: logging_output_type is undefined

# Check collectors base packages availability

- name: Check Rsyslog packages are available
  yum:
    list: "{{ item }}"
  with_items:
    - "{{ rsyslog_base_packages }}"
  register: rsyslog_packages_availability
  when: logging_collector is undefined or logging_collector == 'rsyslog'

- name: Set rsyslog_base_packages_available fact
  set_fact:
    rsyslog_base_packages_available: false
  with_items: "{{ rsyslog_packages_availability.results }}"
  when:
    - item.results == []
    - logging_collector is undefined or logging_collector == 'rsyslog'

- name: Set logging_collector as rsyslog
  set_fact:
    logging_collector: "rsyslog"
  when:
    - rsyslog_base_packages_available
    - logging_collector is undefined

- name: Check Fluentd packages are available
  yum:
    list: "{{ item }}"
  with_items:
    - "{{ fluentd_base_packages }}"
  register: fluentd_packages_availability
  when:
    - not rsyslog_base_packages_available or logging_collector == 'fluentd'

- name: Set fluentd_base_packages_available fact
  set_fact:
    fluentd_base_packages_available: false
  with_items: "{{ fluentd_packages_availability.results }}"
  when:
    - item.results == []
    - not rsyslog_base_packages_available or logging_collector == 'fluentd'

- name: Set logging_collector as fluentd
  set_fact:
    logging_collector: "fluentd"
  when:
    - fluentd_base_packages_available
    - logging_collector is undefined

- name: Validate Fluentd or Rsyslog base packages are available
  debug:
    msg: "Logs collector base packages are not available. Metrics role will not be able to continue"
  when: logging_collector is undefined
  changed_when: true
  notify: set failed validation

- name: Validate logging_collector
  debug:
    msg: "Log collector is missing required base packages. Metrics role will not be able to continue"
  when:
    - not rsyslog_base_packages_available
    - not fluentd_base_packages_available
  changed_when: true
  notify: set failed validation

# TODO add api to add warning message for the user to update its configuration file
- block:

    # Rsyslog validations
    - name: Update user configuration required
      debug:
        msg: "Please update the 'fluentd_elasticsearch_host' to 'elasticsearch_host' in your configuration file. Please see latest documentation"
      when:
        - logging_collector == "rsyslog"
        - fluentd_elasticsearch_host != ""

    - name: If logging collector is rsyslog, validate that the output is elasticsearch
      debug:
        msg: "The defined output target is not supported in Rsyslog, please check documentation and update you configuration."
      when:
        - logging_collector == "rsyslog"
        - (logging_output_type == "fluentd") or (logging_output_type == "file")
      changed_when: true
      notify: set failed validation

    - name: If output plugin is elasticsearch, validate host address is set
      debug:
        msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
      when:
        - logging_collector == "rsyslog"
        - elasticsearch_host == ""
        - logging_output_type == "elasticsearch"
      changed_when: true
      notify: set failed validation

    # Fluentd validations
    - name: If output plugin is elasticsearch, validate host address is set
      debug:
        msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
      when:
        - logging_collector == "fluentd"
        - fluentd_elasticsearch_host == ""
        - logging_output_type == "elasticsearch"
      changed_when: true
      notify: set failed validation

    - name: If output plugin is fluentd, validate host address is set
      debug:
        msg: "oVirt Metrics store is not configured. This host will not be configured to send metrics"
      when:
        - logging_collector == "fluentd"
        - fluentd_fluentd_host is undefined
        - logging_output_type == "fluentd"
      changed_when: true
      notify: set failed validation
  when: logging_collector is defined
