---
- name: Validate fluentd_output_plugin parameter
  fail:
    msg: "'{{ fluentd_output_plugin }}' must be set to either 'elasticsearch' or 'fluentd'."
  when:
    - fluentd_output_plugin != fluentd_output_plugin_elasticsearch
    - fluentd_output_plugin != fluentd_output_plugin_fluentd

- name: Validate fluentd_elasticsearch_host parameter is set when defined output is elasticsearch
  fail:
    msg: "Default output plugin was updated to use elasticsearch plugin. Please set required parameters."
  when:
    - fluentd_output_plugin == fluentd_output_plugin_elasticsearch
    - fluentd_elasticsearch_host == ""
    - fluentd_fluentd_host != ""

- name: Remove elasticsearch output plugin configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-elasticsearch-output.conf'
  when: fluentd_output_plugin != fluentd_output_plugin_elasticsearch
  notify: restart fluentd

- name: Remove secure_forward output plugin configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
  when: fluentd_output_plugin != fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Set fluentd_fluentd_port fact (non-ssl)
  set_fact:
    fluentd_fluentd_port: 24224
  when:
    - not fluentd_use_ssl
    - not fluentd_fluentd_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_fluentd

- name: Set fluentd_port fact (ssl)
  set_fact:
    fluentd_fluentd_port: 24284
  when:
    - fluentd_use_ssl and not fluentd_fluentd_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_fluentd

- name: Set fluentd_elasticsearch_port fact (ssl)
  set_fact:
    fluentd_elasticsearch_port: 9200
  when:
    - fluentd_use_ssl
    - not fluentd_elasticsearch_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_elasticsearch

- name: Install non-ssl client
  template:
    src: forward_no_ssl.conf
    dest: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - not fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Install ssl client
  template:
    src: forward_ssl.conf
    dest: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Install elasticsearch client configuration
  template:
    src: elasticsearch_output.conf
    dest: '{{ fluentd_config_parts_dir }}/30-elasticsearch-output.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_elasticsearch
  notify: restart fluentd
