---
- name: Install collectd package
  yum:
    name: '{{ collectd_package_name }}'
    state: latest
  when: manage_packages|default(true)
  notify: restart collectd

- name: Install collectd plugins on engine
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ collectd_engine_plugin_packages }}'
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is undefined
    - inventory_hostname in groups.engine
  notify: restart collectd

- name: Install collectd plugins on hosts
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ collectd_host_plugin_packages }}'
  when:
    - manage_packages|default(true)
    - ovirt_metrics_host_deploy is defined or inventory_hostname in groups.hosts
  notify: restart collectd

