- block:
    - name: Add dns line to /etc/hosts if create_host_entry true and all-in-one
      lineinfile:
        path: /etc/hosts
        regexp: 'webconsole\.openshift\-web\-console\.svc'
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} etcd.{{ public_hosted_zone }} openshift-master.{{ public_hosted_zone }} openshift.{{ public_hosted_zone }} docker-registry-default.apps.{{ public_hosted_zone }} webconsole.openshift-web-console.svc registry-console-default.apps.{{ public_hosted_zone }} master-etcd-{{ public_hosted_zone }} kibana.{{ public_hosted_zone }} es.{{ public_hosted_zone }}"
        owner: root
        group: root
        mode: 0644

    - name: Set host_dns_entry fact
      set_fact:
        host_dns_entry: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} etcd.{{ public_hosted_zone }} openshift-master.{{ public_hosted_zone }} openshift.{{ public_hosted_zone }} docker-registry-default.apps.{{ public_hosted_zone }} webconsole.openshift-web-console.svc registry-console-default.apps.{{ public_hosted_zone }} master-etcd-{{ public_hosted_zone }} kibana.{{ public_hosted_zone }} es.{{ public_hosted_zone }}"

    - name: Add dns line to local machine /etc/hosts if host_dns_entry file exists
      lineinfile:
        path: /etc/hosts
        regexp: 'webconsole\.openshift\-web\-console\.svc'
        line: "{{ host_dns_entry }}"
        owner: root
        group: root
        mode: 0644
      delegate_to: '{{ item }}'
      with_items:
        - localhost
        - '{{ openshift_ovirt_bastion_machine_name  }}'
  when: openshift_ovirt_all_in_one and create_host_entry|d(false)|bool == true
