- name: Stop and disable fluentd service, if logging collector is Rsyslog
  service:
    name: fluentd
    state: stopped
    enabled: false
  ignore_errors: true

- name: Set ovirt_vds_cluster_name fact
  set_fact:
    ovirt_vds_cluster_name: "{{ host_deploy_cluster_name }}"
  when:
    - host_deploy_cluster_name is defined
    - ovirt_vds_cluster_name is undefined

- name: Check if vdsm log file exist
  stat:
    path: /var/log/vdsm/vdsm.log
  register: vdsm_log_exists
  run_once: true

- name: Check if engine log file exist
  stat:
    path: /var/log/ovirt-engine/engine.log
  register: engine_log_exists
  run_once: true

- name: Set logging facts
  set_fact:
    logging_role_path: "{{ logging_role_path }}"
    ovirt_output_name_prefix: "{{ ovirt_output_name_prefix|d('ovirt') }}"
    collect_ovirt_vdsm_log: "{{ true if vdsm_log_exists.stat.exists else false }}"
    collect_ovirt_engine_log: "{{ true if engine_log_exists.stat.exists else false }}"
    use_omelasticsearch_cert: true
    rsyslog_max_message_size: "64k"

- block:
    - name: Install fluentd elasticsearch CA certificate
      copy:
        content: '{{ fluentd_elasticsearch_ca_cert }}'
        dest: '{{ fluentd_elasticsearch_ca_cert_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Install fluentd elasticsearch client certificate
      copy:
        content: '{{ fluentd_elasticsearch_client_cert }}'
        dest: '{{ fluentd_elasticsearch_client_cert_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Install fluentd elasticsearch client key
      copy:
        content: '{{ fluentd_elasticsearch_client_key }}'
        dest: '{{ fluentd_elasticsearch_client_key_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Set logging_outputs facts
      set_fact:
        logging_outputs:
          - name: ovirt-logs-elasticsearch
            type: elasticsearch
            logs_collections:
              - name: 'ovirt'
            server_host: '{{ elasticsearch_host }}'
            server_port: '{{ elasticsearch_port|d(9200) }}'
            index_prefix: "project.ovirt-logs"
            bulkmode: "on"
            writeoperation: "index"
            bulkid: "id_template"
            dynbulkid: "on"
            retryfailures: "on"
            retryruleset: try_es
            ca_cert: "{{ fluentd_elasticsearch_ca_cert_path }}"
            cert: "{{ fluentd_elasticsearch_client_cert_path }}"
            key: "{{ fluentd_elasticsearch_client_key_path }}"
          - name: ovirt-metrics-elasticsearch
            type: elasticsearch
            logs_collections:
              - name: 'ovirt'
            server_host: '{{ elasticsearch_host }}'
            server_port: '{{ elasticsearch_port|d(9200) }}'
            index_prefix: "project.ovirt-metrics"
            bulkmode: "on"
            writeoperation: "index"
            bulkid: "id_template"
            dynbulkid: "off"
            retryfailures: "off"
            ca_cert: "{{ fluentd_elasticsearch_ca_cert_path }}"
            cert: "{{ fluentd_elasticsearch_client_cert_path }}"
            key: "{{ fluentd_elasticsearch_client_key_path }}"
  when: logging_output_type|default("elasticsearch") == "elasticsearch"

- name: Run rsyslog sub-role
  include_role:
    name: oVirt.metrics/roles/oVirt.linux-system-roles-logging
