---
- name: Stop and disable fluentd service, if logging collector is Rsyslog
  service:
    name: fluentd
    state: stopped
    enabled: false
  ignore_errors: true

- name: Check if vdsm log file exist
  stat:
    path: /var/log/vdsm/vdsm.log
  register: vdsm_log_exists

- name: Check if engine log file exist
  stat:
    path: /var/log/ovirt-engine/engine.log
  register: engine_log_exists

- name: Set collect_ovirt_vdsm_log fact
  set_fact:
    collect_ovirt_vdsm_log: '{{ true if vdsm_log_exists.stat.exists else false }}'
  when: collect_ovirt_vdsm_log is undefined

- name: Set collect_ovirt_engine_log fact
  set_fact:
    collect_ovirt_engine_log: '{{ true if engine_log_exists.stat.exists else false }}'
  when: collect_ovirt_engine_log is undefined

- name: Set logging facts
  set_fact:
    logging_role_path: '{{ logging_role_path }}'
    rsyslog_max_message_size: '{{ rsyslog_max_message_size|d("64k") }}'
    collect_ovirt_collectd_metrics: '{{ collect_ovirt_collectd_metrics|d(true) }}'
    use_omelasticsearch_cert: '{{ use_omelasticsearch_cert|d(true) }}'
    ovirt_vds_cluster_name: '{{ host_deploy_cluster_name|d("default") }}'

- block:
    - name: Install fluentd elasticsearch CA certificate
      copy:
        content: '{{ fluentd_elasticsearch_ca_cert }}'
        dest: '{{ fluentd_elasticsearch_ca_cert_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Install fluentd elasticsearch client certificate
      copy:
        content: '{{ fluentd_elasticsearch_client_cert }}'
        dest: '{{ fluentd_elasticsearch_client_cert_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Install fluentd elasticsearch client key
      copy:
        content: '{{ fluentd_elasticsearch_client_key }}'
        dest: '{{ fluentd_elasticsearch_client_key_path }}'
        owner: '{{ logging_owner }}'
        group: '{{ logging_group }}'
        mode: '{{ logging_config_mode }}'
      when:
        - use_omelasticsearch_cert|d(true) == true

    - name: Set logging_outputs facts
      set_fact:
        logging_outputs:
          - name: ovirt-logs-elasticsearch
            type: elasticsearch
            logs_collections:
              - name: 'ovirt'
            server_host: '{{ elasticsearch_host }}'
            server_port: '{{ elasticsearch_port|d(9200) }}'
            index_prefix: '{{ logs_index_prefix|d("project.ovirt-logs") }}'
            bulkmode: '{{ rsyslog_elasticsearch_bulkmode_logs|d("on") }}'
            writeoperation: '{{ rsyslog_elasticsearch_writeoperation_logs|d("create") }}'
            bulkid: '{{ rsyslog_elasticsearch_bulkid_logs|d("id_template") }}'
            dynbulkid: '{{ rsyslog_elasticsearch_dynbulkid_logs|d("on") }}'
            retryfailures: '{{ rsyslog_elasticsearch_retryfailures_logs|d("on") }}'
            retryruleset: '{{ rsyslog_elasticsearch_retryruleset_logs|d("try_es") }}'
            usehttps: '{{ rsyslog_elasticsearch_usehttps_logs|d("on") }}'
#            allowUnsignedCerts: '{{ logs_allowUnsignedCerts|d("on") }}'
            ca_cert: '{{ fluentd_elasticsearch_ca_cert_path }}'
            cert: '{{ fluentd_elasticsearch_client_cert_path }}'
            key: '{{ fluentd_elasticsearch_client_key_path }}'
          - name: ovirt-metrics-elasticsearch
            type: elasticsearch
            logs_collections:
              - name: 'ovirt'
            server_host: '{{ elasticsearch_host }}'
            server_port: '{{ elasticsearch_port|d(9200) }}'
            index_prefix: '{{ rsyslog_elasticsearch_index_prefix_metrics|d("project.ovirt-metrics") }}'
            bulkmode: '{{ rsyslog_elasticsearch_bulkmode_metrics|d("on") }}'
            writeoperation: '{{ rsyslog_elasticsearch_writeoperation_metrics|d("create") }}'
            bulkid: '{{ rsyslog_elasticsearch_bulkid_metrics|d("id_template") }}'
            dynbulkid: '{{ rsyslog_elasticsearch_dynbulkid_metrics|d("on") }}'
            retryfailures: '{{ rsyslog_elasticsearch_retryfailures_metrics|d("off") }}'
            retryruleset: '{{ rsyslog_elasticsearch_retryruleset_metrics|d("try_es") }}'
            usehttps: '{{ rsyslog_elasticsearch_usehttps_metrics|d("on") }}'
#            allowUnsignedCerts: '{{ metrics_allowUnsignedCerts|d("on") }}'
            ca_cert: '{{ fluentd_elasticsearch_ca_cert_path }}'
            cert: '{{ fluentd_elasticsearch_client_cert_path }}'
            key: '{{ fluentd_elasticsearch_client_key_path }}'
  when: logging_output_type|default('elasticsearch') == 'elasticsearch'

- name: Run rsyslog sub-role
  include_role:
    name: oVirt.metrics/roles/oVirt.linux-system-roles-logging
