---
- block:
    - name: Generate engine ssh key
      shell: "ssh-keygen -y -f {{ ovirt_engine_id_rsa_path }}/engine_id_rsa > ./engine_id_rsa.pub"

    - name: Update installer machine name if set by the user
      set_fact:
        openshift_ovirt_bastion_machine_name: metrics-store-installer
      when: openshift_ovirt_bastion_machine_name is undefined

    - name: Check if secure_vars.yaml file exist
      stat:
        path: '{{ ovirt_metrics_pkg_sysconf_dir }}/secure_vars.yaml'
      register: secure_vars_file_exists

    - name: Include oVirt metrics secure_vars.yaml file
      include_vars:
        file: '{{ ovirt_metrics_pkg_sysconf_dir }}/secure_vars.yaml'
      when: secure_vars_file_exists.stat.exists
      no_log: true

    - name: Install metrics store machines
      include_role:
        name: '{{ origin_on_ovirt_role_path }}'
      vars:
        ssh_key: "{{ lookup('file', './engine_id_rsa.pub') }}"
        origin_on_ovirt_secure_vars_file: '{{ ovirt_metrics_pkg_sysconf_dir }}/secure_vars.yaml'

    - name: Generate template files
      template:
        src: '{{ item }}.template'
        dest: '{{ origin_on_ovirt_files_path }}/{{ item }}'
        mode: 0644
      with_items:
        - ovirt_metrics_curator_configmap.yaml
        - metrics_store_post_installation.yaml

    - name: Copy files to bastion machine
      copy:
        src: '{{ origin_on_ovirt_files_path }}/{{ item }}'
        dest: '{{ openshift_ansible_files_path }}/{{ item }}'
        mode: 0644
      delegate_to: '{{ openshift_ovirt_bastion_machine_name }}'
      with_items:
        - ovirt_metrics_curator_configmap.yaml
        - metrics_store_post_installation.yaml

  always:
    - name: Delete engine_id_rsa.pub
      file:
        path: engine_id_rsa.pub
        state: absent
