---
- name: Initial validations
  hosts: engine

  roles:
    - role: oVirt.metrics/roles/oVirt.initial-validations

- name: Post metrics store installation roles
  hosts: metrics_store

  roles:
    - role: oVirt.metrics/roles/oVirt.metrics-store-setup
      when: hostvars['localhost']['failed_validation'] is undefined

- name: Configure Metrics
  hosts: engine:hosts

  roles:
    - role: oVirt.metrics/roles/oVirt.fluentd
      when: hostvars['localhost']['failed_validation'] is undefined
    - role: oVirt.metrics/roles/oVirt.collectd
      when: hostvars['localhost']['failed_validation'] is undefined
