---
- name: Initial validations
  hosts: engine

  roles:
    - oVirt.metrics/roles/oVirt.initial-validations

- name: Post metrics store installation roles
  hosts: metrics_store

  roles:
    - oVirt.metrics/roles/oVirt.metrics-store-setup

- name: Configure Metrics
  hosts: engine:hosts

  roles:
    - oVirt.metrics/roles/oVirt.fluentd
    - oVirt.metrics/roles/oVirt.collectd
