---
- name: oVirt metrics store installation
  hosts: engine

  roles:
    - role: oVirt.metrics/roles/oVirt.initial-validations
      vars:
        check_logging_collectors: false
    - role: oVirt.metrics/roles/oVirt.metrics-store-installation
      when: failed_validation is undefined
