---
- name: oVirt metrics store installation - Create installer virtual machine
  hosts: engine

  tasks:
  - include_role:
      name: oVirt.metrics/roles/oVirt.initial-validations
    vars:
      check_logging_collectors: false

  - include_role:
      name: oVirt.metrics/roles/oVirt.metrics-store-installation
    when: failed_validation is undefined
