---
- name: Install collectd plugins
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ collectd_engine_plugin_packages }}'
  when: manage_packages|default(true)
  notify: restart collectd
